const initialCategories = ['Combustível','Pedágio','Estacionamento','Lavagem','Almoço','Lanche','Café/água','Outros'];
const initialUses = ['Trabalho Uber'];
const key = 'meuLucroUber.v1';
let state = load(); let view = 'dashboard'; let editing = null; let maintenanceEditing = null;
function load(){try{const saved=JSON.parse(localStorage.getItem(key));if(saved){saved.categories=(saved.categories?.length?saved.categories:initialCategories).filter(x=>!['Manutenção','Seguro','IPVA/licenciamento','Financiamento/aluguel','Multas'].includes(x));saved.uses=['Trabalho Uber'];saved.maintenance=Array.isArray(saved.maintenance)?saved.maintenance:[];return saved;}}catch(e){}return {incomes:[],expenses:[],maintenance:[],categories:[...initialCategories],uses:initialUses};}
function save(){localStorage.setItem(key,JSON.stringify(state));}
const money = n => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0));
const number = n => new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(Number(n||0));
const id = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2);
const today = () => new Date().toISOString().slice(0,10);
const work = item => item.use === 'Trabalho Uber';
const escape = value => String(value||'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400);}
function total(items, predicate=()=>true){return items.filter(predicate).reduce((sum,item)=>sum+Number(item.amount||0),0);}
function stats(){const income=total(state.incomes,work), expense=total(state.expenses,work);const km=state.incomes.filter(work).reduce((s,x)=>s+Number(x.km||0),0)+state.expenses.filter(work).reduce((s,x)=>s+Number(x.km||0),0);const hours=state.incomes.filter(work).reduce((s,x)=>s+Number(x.hours||0),0);return {income,expense,profit:income-expense,km,hours};}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const pages={dashboard,income,expense,reports,settings};if(view==='personal'&&typeof personal==='function'){personal();return;}document.querySelector('#app').innerHTML=pages[view]?pages[view]() : dashboard();bind();}
function dashboard(){const s=stats();return `<div class="section-head"><div><h2>Visão geral</h2><p class="hint">Apenas o resultado do trabalho Uber.</p></div></div><div class="summary-grid"><article class="card metric"><span>Lucro líquido</span><strong class="${s.profit>=0?'positive':'negative'}">${money(s.profit)}</strong></article><article class="card metric"><span>Ganhos Uber</span><strong class="positive">${money(s.income)}</strong></article><article class="card metric"><span>Gastos Uber</span><strong class="negative">${money(s.expense)}</strong></article><article class="card metric"><span>Lucro por hora</span><strong>${money(s.hours?s.profit/s.hours:0)}</strong></article><article class="card metric"><span>Lucro por km</span><strong>${money(s.km?s.profit/s.km:0)}</strong></article></div><h3 class="section-title">Ações rápidas</h3><div class="split"><button class="button" data-go="income">Registrar ganho</button><button class="button secondary" data-go="expense">Registrar gasto</button></div><h3 class="section-title">Últimos lançamentos</h3>${entriesList([...state.incomes.map(x=>({...x,kind:'income'})),...state.expenses.map(x=>({...x,kind:'expense'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5),false)}`;}
function income(){return form('income');} function expense(){return form('expense');}
function form(kind){const current=editing?.kind===kind?editing.item:null;const isIncome=kind==='income';const title=current?'Editar '+(isIncome?'ganho':'gasto'):'Novo '+(isIncome?'ganho':'gasto');return `<div class="section-head"><div><h2>${title}</h2><p class="hint">Todos os campos podem ser modificados depois.</p></div></div><form id="entryForm" class="form-card" data-kind="${kind}"><div class="form-grid"><label>Data<input required name="date" type="date" value="${current?.date||today()}" /></label>${isIncome?`<label>Valor líquido (R$)<input required min="0" step="0.01" name="amount" type="number" value="${current?.amount||''}" /></label><label>Gorjetas (R$)<input min="0" step="0.01" name="tips" type="number" value="${current?.tips||''}" /></label><label>Quantidade de viagens<input min="0" name="trips" type="number" value="${current?.trips||''}" /></label><label>Horas trabalhadas<input min="0" step="0.1" name="hours" type="number" value="${current?.hours||''}" /></label>`:`<label>Categoria<select required name="category">${options(state.categories,current?.category)}</select></label><label>Valor (R$)<input required min="0" step="0.01" name="amount" type="number" value="${current?.amount||''}" /></label><label>Quilometragem atual<input min="0" step="0.1" name="odometer" type="number" value="${current?.odometer||''}" /></label>`}<label>Observação<textarea name="note" placeholder="Ex.: abastecimento no posto...">${escape(current?.note)}</textarea></label></div><div class="form-actions"><button type="button" class="button secondary" data-go="dashboard">Cancelar</button><button class="button" type="submit">${current?'Salvar alterações':'Adicionar lançamento'}</button></div></form>`;}
function options(items, selected){return items.map(x=>`<option ${x===selected?'selected':''}>${escape(x)}</option>`).join('');}
function entriesList(items, actions=true){if(!items.length)return '<div class="empty">Ainda não há lançamentos neste espaço.</div>';return `<div class="list">${items.map(item=>`<article class="row"><div><div class="row-title">${item.kind==='income'?'Ganho Uber':escape(item.category)}</div><div class="row-sub">${item.date.split('-').reverse().join('/')} · ${item.use==='Lazer/pessoal'?'Pessoal':'Uber'}${item.note?' · '+escape(item.note):''}</div></div><div><div class="row-value ${item.kind==='income'?'positive':'negative'}">${item.kind==='income'?'+':'−'} ${money(Number(item.amount)+Number(item.tips||0))}</div>${actions?`<div class="row-actions"><button class="text-button" data-edit="${item.kind}:${item.id}">Editar</button><button class="text-button delete" data-delete="${item.kind}:${item.id}">Excluir</button></div>`:''}</div></article>`).join('')}</div>`;}
function reports(){const s=stats();const costs=state.expenses.filter(work).reduce((a,x)=>{a[x.category]=(a[x.category]||0)+Number(x.amount);return a;},{});const max=Math.max(1,...Object.values(costs));return `<div class="section-head"><div><h2>Relatórios</h2><p class="hint">Resumo geral dos seus lançamentos.</p></div></div><div class="summary-grid"><article class="card metric"><span>Receita total</span><strong>${money(s.income)}</strong></article><article class="card metric"><span>Despesa de trabalho</span><strong>${money(s.expense)}</strong></article><article class="card metric"><span>Quilômetros de trabalho</span><strong>${number(s.km)} km</strong></article></div><h3 class="section-title">Gastos do trabalho por categoria</h3>${Object.keys(costs).length?`<div class="card">${Object.entries(costs).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="row-sub" style="margin:9px 0">${escape(name)} <b style="float:right;color:var(--ink)">${money(value)}</b><div class="bar"><i style="width:${value/max*100}%"></i></div></div>`).join('')}</div>`:'<div class="empty">Cadastre gastos de trabalho para ver a divisão por categoria.</div>'}`;}
function settings(){const m=maintenanceEditing;return `<div class="section-head"><div><h2>Ajustes</h2><p class="hint">Personalize as categorias e acompanhe a manutenção.</p></div></div>${settingGroup('Categorias de gastos','category')}<div class="setting-group"><h3 class="section-title">Manutenções</h3><form id="maintenanceForm" class="form-card"><div class="form-grid"><label>Serviço<input required name="service" placeholder="Troca de óleo" value="${escape(m?.service)}" /></label><label>Data realizada<input name="date" type="date" value="${m?.date||''}" /></label><label>Próxima manutenção<input name="nextDate" type="date" value="${m?.nextDate||''}" /></label><label>Quilometragem prevista<input min="0" name="km" type="number" value="${m?.km||''}" /></label><label>Próxima manutenção aos (km)<input min="0" name="nextKm" type="number" value="${m?.nextKm||''}" /></label></div><div class="form-actions">${m?'<button class="button secondary" id="cancelMaintenance" type="button">Cancelar</button>':''}<button class="button" type="submit">${m?'Salvar manutenção':'Adicionar manutenção'}</button></div></form><div class="list" style="margin-top:10px">${state.maintenance.length?state.maintenance.map(x=>`<div class="row"><div><div class="row-title">${escape(x.service)}</div><div class="row-sub">${x.date?'Realizada: '+x.date.split('-').reverse().join('/'):''}${x.nextDate?' · Próxima: '+x.nextDate.split('-').reverse().join('/'):''}${x.km?' · '+number(x.km)+' km':''}${x.nextKm?' · Próxima aos '+number(x.nextKm)+' km':''}</div></div><div><button class="text-button" data-maint-edit="${x.id}">Editar</button><button class="text-button delete" data-maint-delete="${x.id}">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhuma manutenção cadastrada.</div>'}</div></div><div class="setting-group"><h3 class="section-title">Dados</h3><button class="button danger" id="clearData">Excluir todos os dados</button><p class="hint">Essa ação solicita confirmação e não pode ser desfeita.</p></div>`;}
function settingGroup(title,type){const values=type==='category'?state.categories:state.uses;return `<section class="setting-group"><h3 class="section-title">${title}</h3><div class="add-inline"><input id="new-${type}" placeholder="Adicionar novo" /><button class="button small" data-add-setting="${type}">Adicionar</button></div><div class="list">${values.map((x,i)=>`<div class="row"><span class="row-title">${escape(x)}</span><div><button class="text-button" data-rename-setting="${type}:${i}">Renomear</button><button class="text-button delete" data-remove-setting="${type}:${i}">Excluir</button></div></div>`).join('')}</div></section>`;}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;editing=null;render();});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;editing=null;render();});const form=document.querySelector('#entryForm');if(form)form.onsubmit=saveEntry;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editEntry(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.delete));document.querySelectorAll('[data-add-setting]').forEach(b=>b.onclick=()=>addSetting(b.dataset.addSetting));document.querySelectorAll('[data-rename-setting]').forEach(b=>b.onclick=()=>renameSetting(b.dataset.renameSetting));document.querySelectorAll('[data-remove-setting]').forEach(b=>b.onclick=()=>removeSetting(b.dataset.removeSetting));const m=document.querySelector('#maintenanceForm');if(m)m.onsubmit=saveMaintenance;document.querySelectorAll('[data-maint-edit]').forEach(b=>b.onclick=()=>{maintenanceEditing=state.maintenance.find(x=>x.id===b.dataset.maintEdit);render();});const cancelMaintenance=document.querySelector('#cancelMaintenance');if(cancelMaintenance)cancelMaintenance.onclick=()=>{maintenanceEditing=null;render();};document.querySelectorAll('[data-maint-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta manutenção?')){state.maintenance=state.maintenance.filter(x=>x.id!==b.dataset.maintDelete);save();render();}});const clear=document.querySelector('#clearData');if(clear)clear.onclick=()=>{if(confirm('Excluir todos os dados do aplicativo?')){localStorage.removeItem(key);state=load();render();toast('Todos os dados foram excluídos.');}};}
function saveEntry(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));const kind=e.target.dataset.kind;const item={...data,amount:Number(data.amount),tips:Number(data.tips||0),km:0,hours:Number(data.hours||0),trips:Number(data.trips||0),odometer:Number(data.odometer||0),use:'Trabalho Uber'};if(editing){const list=kind==='income'?state.incomes:state.expenses;Object.assign(list.find(x=>x.id===editing.item.id),item);toast('Lançamento atualizado.');}else{item.id=id();(kind==='income'?state.incomes:state.expenses).push(item);toast('Lançamento adicionado.');}save();editing=null;view='dashboard';render();}
function editEntry(value){const [kind,itemId]=value.split(':');editing={kind,item:(kind==='income'?state.incomes:state.expenses).find(x=>x.id===itemId)};view=kind;render();}
function deleteEntry(value){const [kind,itemId]=value.split(':');if(!confirm('Excluir este lançamento? Esta ação não pode ser desfeita.'))return;const prop=kind==='income'?'incomes':'expenses';state[prop]=state[prop].filter(x=>x.id!==itemId);save();render();toast('Lançamento excluído.');}
function addSetting(type){if(type!=='category')return;const input=document.querySelector('#new-'+type),value=input.value.trim(),prop='categories';if(!value)return;if(state[prop].includes(value))return toast('Esse item já existe.');state[prop].push(value);save();render();}
function renameSetting(value){const [type,index]=value.split(':');if(type!=='category')return;const prop='categories',old=state[prop][index],next=prompt('Novo nome:',old);if(!next||!next.trim()||state[prop].includes(next.trim()))return;state[prop][index]=next.trim();state.expenses.forEach(x=>{if(x.category===old)x.category=next.trim();});save();render();}
function removeSetting(value){const [type,index]=value.split(':');if(type!=='category')return;const prop='categories',name=state[prop][index];if(state[prop].length===1)return toast('Mantenha pelo menos uma opção.');if(!confirm(`Excluir "${name}"? Os lançamentos antigos continuarão registrados.`))return;state[prop].splice(index,1);save();render();}
function saveMaintenance(e){e.preventDefault();const x=Object.fromEntries(new FormData(e.target));x.nextDate=x.nextDate||'';x.nextKm=x.nextKm||'';if(maintenanceEditing){Object.assign(state.maintenance.find(item=>item.id===maintenanceEditing.id),x);maintenanceEditing=null;toast('Manutenção atualizada.');}else{state.maintenance.push({...x,id:id()});toast('Manutenção cadastrada.');}save();render();}
document.querySelector('#exportButton').onclick=()=>{const rows=[['Tipo','Data','Valor','Categoria','Uso','KM','Horas','Viagens','Observação'],...state.incomes.map(x=>['Ganho',x.date,Number(x.amount)+Number(x.tips||0),'',x.use,x.km,x.hours,x.trips,x.note]),...state.expenses.map(x=>['Gasto',x.date,x.amount,x.category,x.use,x.km,'','',x.note])];const csv=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(';')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='meu-lucro-uber.csv';a.click();URL.revokeObjectURL(url);toast('Planilha CSV exportada.');};
render();

// Reserva mensal: uma meta de caixa separada dos gastos já registrados.
const dashboardBase = dashboard;
dashboard = function () {
  const reserve = state.reserve || { daily: 0 };
  const daily = Number(reserve.daily ?? (Number(reserve.monthly || 0) / Math.max(1, Number(reserve.workDays || 26))));
  const reserveCard = `<h3 class="section-title">Reserva diária do carro</h3><article class="card metric"><span>Quanto guardar hoje para as despesas do carro</span><strong class="positive">${money(daily)}</strong><p class="hint">Meta diária para seguro, manutenção, documentação, parcela e outras despesas.</p><button class="text-button" data-go="settings">Editar meta diária</button></article>`;
  return dashboardBase().replace('<h3 class="section-title">Últimos lançamentos</h3>', reserveCard + '<h3 class="section-title">Últimos lançamentos</h3>');
};

const settingsBase = settings;
settings = function () {
  const reserve = state.reserve || { daily: 0 };
  const daily = Number(reserve.daily ?? (Number(reserve.monthly || 0) / Math.max(1, Number(reserve.workDays || 26))));
  const reserveForm = `<div class="setting-group"><h3 class="section-title">Reserva diária do carro</h3><p class="hint">Defina quanto deseja guardar por dia para seguro, manutenção, documentação, parcela e outras despesas.</p><form id="reserveForm" class="form-card"><div class="form-grid"><label>Meta diária de reserva (R$)<input required min="0" step="0.01" name="daily" type="number" value="${daily}" /></label></div><div class="form-actions"><button class="button" type="submit">Salvar meta diária</button></div></form></div>`;
  return settingsBase().replace('<div class="setting-group"><h3 class="section-title">Manutenções</h3>', reserveForm + '<div class="setting-group"><h3 class="section-title">Manutenções</h3>');
};

document.addEventListener('submit', event => {
  if (event.target.id !== 'reserveForm') return;
  event.preventDefault();
  const data = Object.fromEntries(new FormData(event.target));
  state.reserve = { daily: Number(data.daily || 0) };
  save();
  toast('Meta de reserva diária atualizada.');
  render();
});

render();
