const initialCategories=['Combustível','Pedágio','Estacionamento','Lavagem','GRT','Almoço','Lanche','Café/água','Outros'];
const initialUses=['Trabalho Uber'];
const key='meuLucroUber.v1';
const blockedCategories=new Set(['IPVA 3/3','IPVA/licenciamento','Seguro','Manutenção','Multas']);
let state=load(),view='dashboard',editing=null,maintenanceEditing=null;
function load(){try{const saved=JSON.parse(localStorage.getItem(key));if(saved){saved.categories=(Array.isArray(saved.categories)?saved.categories:[]).filter(x=>!blockedCategories.has(String(x).trim()));if(!saved.categories.includes('GRT'))saved.categories.push('GRT');saved.uses=['Trabalho Uber'];saved.maintenance=Array.isArray(saved.maintenance)?saved.maintenance:[];return saved;}}catch(e){}return{incomes:[],expenses:[],maintenance:[],categories:[...initialCategories],uses:[...initialUses]};}
function save(){localStorage.setItem(key,JSON.stringify(state));}
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n||0));
const number=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(Number(n||0));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const today=()=>new Date().toISOString().slice(0,10);
const work=item=>item.use==='Trabalho Uber';
const personalItem=item=>item.use==='Lazer/pessoal'||item.use==='Pessoal';
const escape=value=>String(value||'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400);}
function total(items,predicate=()=>true){return items.filter(predicate).reduce((sum,item)=>sum+Number(item.amount||0),0);}
function stats(){const income=total(state.incomes,work),expense=total(state.expenses,work);const km=state.incomes.filter(work).reduce((s,x)=>s+Number(x.km||0),0)+state.expenses.filter(work).reduce((s,x)=>s+Number(x.km||0),0);const hours=state.incomes.filter(work).reduce((s,x)=>s+Number(x.hours||0),0);return{income,expense,profit:income-expense,km,hours};}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const pages={dashboard,income,expense,reports,settings};if(view==='personal'&&typeof personal==='function'){personal();return;}document.querySelector('#app').innerHTML=pages[view]?pages[view]():dashboard();bind();}
function dashboard(){const s=stats();const recent=[...state.incomes.filter(work).map(x=>({...x,kind:'income'})),...state.expenses.filter(work).map(x=>({...x,kind:'expense'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);return `<div class="section-head"><div><h2>Visão geral</h2><p class="hint">Apenas o resultado do trabalho Uber.</p></div></div><div class="summary-grid"><article class="card metric"><span>Lucro líquido</span><strong class="${s.profit>=0?'positive':'negative'}">${money(s.profit)}</strong></article><article class="card metric"><span>Ganhos Uber</span><strong class="positive">${money(s.income)}</strong></article><article class="card metric"><span>Gastos Uber</span><strong class="negative">${money(s.expense)}</strong></article><article class="card metric"><span>Lucro por hora</span><strong>${money(s.hours?s.profit/s.hours:0)}</strong></article><article class="card metric"><span>Lucro por km</span><strong>${money(s.km?s.profit/s.km:0)}</strong></article></div><h3 class="section-title">Ações rápidas</h3><div class="split"><button class="button" data-go="income">Registrar ganho</button><button class="button secondary" data-go="expense">Registrar gasto</button></div><h3 class="section-title">Últimos lançamentos</h3>${entriesList(recent,false)}`;}
function income(){return form('income');}function expense(){return form('expense');}
function form(kind){const current=editing?.kind===kind?editing.item:null,isIncome=kind==='income';return `<div class="section-head"><div><h2>${current?'Editar '+(isIncome?'ganho':'gasto'):'Novo '+(isIncome?'ganho':'gasto')}</h2><p class="hint">Todos os campos podem ser modificados depois.</p></div></div><form id="entryForm" class="form-card" data-kind="${kind}"><div class="form-grid"><label>Data<input required name="date" type="date" value="${current?.date||today()}" /></label>${isIncome?`<label>Valor líquido (R$)<input required min="0" step="0.01" name="amount" type="number" value="${current?.amount||''}" /></label><label>Gorjetas (R$)<input min="0" step="0.01" name="tips" type="number" value="${current?.tips||''}" /></label><label>Quantidade de viagens<input min="0" name="trips" type="number" value="${current?.trips||''}" /></label><label>Horas trabalhadas<input min="0" step="0.1" name="hours" type="number" value="${current?.hours||''}" /></label>`:`<label>Categoria<select required name="category">${options(state.categories,current?.category)}</select></label><label>Valor (R$)<input required min="0" step="0.01" name="amount" type="number" value="${current?.amount||''}" /></label><label>Quilometragem atual<input min="0" step="0.1" name="odometer" type="number" value="${current?.odometer||''}" /></label>`}<label>Observação<textarea name="note">${escape(current?.note)}</textarea></div><div class="form-actions"><button type="button" class="button secondary" data-go="dashboard">Cancelar</button><button class="button" type="submit">${current?'Salvar alterações':'Adicionar lançamento'}</button></div></form>`;}
function options(items,selected){const clean=[...new Set((Array.isArray(items)?items:[]).map(x=>String(x).trim()).filter(x=>x&&!blockedCategories.has(x)))];if(!clean.includes('GRT'))clean.splice(Math.min(4,clean.length),0,'GRT');return clean.map(x=>`<option ${x===selected?'selected':''}>${escape(x)}</option>`).join('');}
function entriesList(items,actions=true){if(!items.length)return '<div class="empty">Ainda não há lançamentos neste espaço.</div>';return `<div class="list">${items.map(item=>`<article class="row"><div><div class="row-title">${item.kind==='income'?'Ganho Uber':escape(item.category)}</div><div class="row-sub">${item.date.split('-').reverse().join('/')} · Uber${item.note?' · '+escape(item.note):''}</div></div><div><div class="row-value ${item.kind==='income'?'positive':'negative'}">${item.kind==='income'?'+':'−'} ${money(Number(item.amount)+Number(item.tips||0))}</div>${actions?`<div class="row-actions"><button class="text-button" data-edit="${item.kind}:${item.id}">Editar</button><button class="text-button delete" data-delete="${item.kind}:${item.id}">Excluir</button></div>`:''}</div></article>`).join('')}</div>`;}
function reports(){const s=stats();const costs=state.expenses.filter(work).reduce((a,x)=>{a[x.category]=(a[x.category]||0)+Number(x.amount);return a;},{});const max=Math.max(1,...Object.values(costs));return `<div class="section-head"><div><h2>Relatórios</h2><p class="hint">Resumo geral dos seus lançamentos.</p></div></div><div class="summary-grid"><article class="card metric"><span>Receita total</span><strong>${money(s.income)}</strong></article><article class="card metric"><span>Despesa de trabalho</span><strong>${money(s.expense)}</strong></article><article class="card metric"><span>Quilômetros de trabalho</span><strong>${number(s.km)} km</strong></article></div><h3 class="section-title">Gastos do trabalho por categoria</h3>${Object.keys(costs).length?`<div class="card">${Object.entries(costs).sort((a,b)=>b[1]-a[1]).map(([name,value])=>`<div class="row-sub" style="margin:9px 0">${escape(name)} <b style="float:right;color:var(--ink)">${money(value)}</b><div class="bar"><i style="width:${value/max*100}%"></i></div></div>`).join('')}</div>`:'<div class="empty">Cadastre gastos de trabalho para ver a divisão por categoria.</div>'}`;}
function settings(){return `<div class="section-head"><div><h2>Ajustes</h2><p class="hint">Personalize as categorias e acompanhe a manutenção.</p></div></div><section class="setting-group"><h3 class="section-title">Categorias de gastos</h3><div class="add-inline"><input id="new-category" placeholder="Adicionar novo" /><button class="button small" data-add-setting="category">Adicionar</button></div><div class="list">${state.categories.filter(x=>!blockedCategories.has(String(x).trim())).map((x,i)=>`<div class="row"><span class="row-title">${escape(x)}</span><div><button class="text-button" data-rename-setting="category:${i}">Renomear</button><button class="text-button delete" data-remove-setting="category:${i}">Excluir</button></div></div>`).join('')}</div></section><div class="setting-group"><h3 class="section-title">Manutenções</h3><p class="hint">Cadastre a data realizada e a próxima manutenção.</p></div>`;}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;editing=null;render();});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;editing=null;render();});const form=document.querySelector('#entryForm');if(form)form.onsubmit=saveEntry;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editEntry(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.delete));document.querySelectorAll('[data-add-setting]').forEach(b=>b.onclick=()=>addSetting(b.dataset.addSetting));document.querySelectorAll('[data-rename-setting]').forEach(b=>b.onclick=()=>renameSetting(b.dataset.renameSetting));document.querySelectorAll('[data-remove-setting]').forEach(b=>b.onclick=()=>removeSetting(b.dataset.removeSetting));}
function saveEntry(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),kind=e.target.dataset.kind,item={...data,amount:Number(data.amount),tips:Number(data.tips||0),hours:Number(data.hours||0),trips:Number(data.trips||0),odometer:Number(data.odometer||0),use:'Trabalho Uber'};if(kind==='expense'&&blockedCategories.has(String(item.category).trim()))item.category='GRT';if(editing){const list=kind==='income'?state.incomes:state.expenses;Object.assign(list.find(x=>x.id===editing.item.id),item);toast('Lançamento atualizado.');}else{item.id=id();(kind==='income'?state.incomes:state.expenses).push(item);toast('Lançamento adicionado.');}save();editing=null;view='dashboard';render();}
function editEntry(value){const[kind,itemId]=value.split(':');editing={kind,item:(kind==='income'?state.incomes:state.expenses).find(x=>x.id===itemId)};view=kind;render();}
function deleteEntry(value){const[kind,itemId]=value.split(':');if(!confirm('Excluir este lançamento? Esta ação não pode ser desfeita.'))return;const prop=kind==='income'?'incomes':'expenses';state[prop]=state[prop].filter(x=>x.id!==itemId);save();render();toast('Lançamento excluído.');}
function addSetting(type){if(type!=='category')return;const input=document.querySelector('#new-'+type),value=input.value.trim();if(!value)return;if(blockedCategories.has(value))return toast('Essa categoria é reservada para Contas e manutenção.');if(state.categories.includes(value))return toast('Esse item já existe.');state.categories.push(value);save();render();}
function renameSetting(value){const[type,index]=value.split(':');if(type!=='category')return;const old=state.categories[index],next=prompt('Novo nome:',old);if(!next||!next.trim()||blockedCategories.has(next.trim())||state.categories.includes(next.trim()))return;state.categories[index]=next.trim();state.expenses.forEach(x=>{if(x.category===old)x.category=next.trim();});save();render();}
function removeSetting(value){const[type,index]=value.split(':');if(type!=='category')return;const name=state.categories[index];if(blockedCategories.has(String(name).trim()))return;if(!confirm(`Excluir "${name}"? Os lançamentos antigos continuarão registrados.`))return;state.categories.splice(index,1);save();render();}
render();