const assert=require('node:assert/strict');
const fs=require('node:fs');
const sync=fs.readFileSync('sincronizacao-v3.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const calc=fs.readFileSync('calculadora-km.js','utf8');
const pessoal=fs.readFileSync('pessoal-fix.js','utf8');
const reminders=fs.readFileSync('lembretes-contas.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

assert.match(sync,/meuLucroUber\.v1/);
assert.match(sync,/nowMain/);
assert.match(sync,/sending/);
assert.match(sync,/lopes-tur-sync-v4/);
assert.match(index,/sincronizacao-v3\.js\?v=4/);
assert.match(index,/sw\.js\?v=16/);
assert.match(calc,/const kmValue=km\*rate/);
assert.match(calc,/serviceMetric\.hidden=service==='manual'/);
assert.match(pessoal,/name="dueDate"/);
assert.match(pessoal,/lopesTurCalendarioPessoal\.syncCalendar/);
assert.match(reminders,/reminderDays:1/);
assert.match(sw,/typeof item\.reminderDays==='number'\?n===item\.reminderDays/);
console.log('Lopes Tur regressao estrutural: OK');
